#!/bin/bash
#
# Checks changed files in stage area by running npm test and lint for each commit.
#

PATCH_FILE="working-tree.patch"

function cleanup {
    exit_code=$?
    if [ -f "$PATCH_FILE" ]; then
        git apply "$PATCH_FILE" 2> /dev/null
        rm "$PATCH_FILE"
    fi
    exit $exit_code
}

trap cleanup EXIT SIGINT SIGHUP

# Cancel any changes to the working tree that are not going to be committed
git diff > "$PATCH_FILE"
git checkout -- .


npm run test:nowatch || exit 1
npm run lint || exit 1
