import { NutritionDetailsAPIModel } from "../models/NutritionDetailsAPIModel";

export const beefData: NutritionDetailsAPIModel = {
  uri: "http://www.edamam.com/ontologies/edamam.owl#recipe_2036f653f23c4a17873fe43765f9dd1d",
  yield: 2.0,
  calories: 130,
  totalWeight: 100.0,
  dietLabels: ["HIGH_PROTEIN", "LOW_CARB", "LOW_SODIUM"],
  healthLabels: [
    "LOW_FAT_ABS",
    "SUGAR_CONSCIOUS",
    "LOW_SUGAR",
    "KIDNEY_FRIENDLY",
    "KETO_FRIENDLY",
    "PALEO",
    "SPECIFIC_CARBS",
    "DAIRY_FREE",
    "GLUTEN_FREE",
    "WHEAT_FREE",
    "EGG_FREE",
    "MILK_FREE",
    "PEANUT_FREE",
    "TREE_NUT_FREE",
    "SOY_FREE",
    "FISH_FREE",
    "SHELLFISH_FREE",
    "PORK_FREE",
    "CRUSTACEAN_FREE",
    "CELERY_FREE",
    "MUSTARD_FREE",
    "SESAME_FREE",
    "LUPINE_FREE",
    "MOLLUSK_FREE",
    "ALCOHOL_FREE",
    "NO_OIL_ADDED",
    "NO_SUGAR_ADDED",
    "SULPHITE_FREE",
    "FODMAP_FREE",
    "KOSHER",
  ],
  cautions: [],
  totalNutrients: {
    ENERC_KCAL: {
      label: "Energy",
      quantity: 130.0,
      unit: "kcal",
    },
    FAT: {
      label: "Total lipid (fat)",
      quantity: 4.81,
      unit: "g",
    },
    FASAT: {
      label: "Fatty acids, total saturated",
      quantity: 1.988,
      unit: "g",
    },
    FATRN: {
      label: "Fatty acids, total trans",
      quantity: 0.25,
      unit: "g",
    },
    FAMS: {
      label: "Fatty acids, total monounsaturated",
      quantity: 2.51,
      unit: "g",
    },
    FAPU: {
      label: "Fatty acids, total polyunsaturated",
      quantity: 0.31,
      unit: "g",
    },
    CHOCDF: {
      label: "Carbohydrate, by difference",
      quantity: 0.12,
      unit: "g",
    },
    FIBTG: {
      label: "Fiber, total dietary",
      quantity: 0.0,
      unit: "g",
    },
    SUGAR: {
      label: "Sugars, total",
      quantity: 0.0,
      unit: "g",
    },
    PROCNT: {
      label: "Protein",
      quantity: 21.64,
      unit: "g",
    },
    CHOLE: {
      label: "Cholesterol",
      quantity: 63.0,
      unit: "mg",
    },
    NA: {
      label: "Sodium, Na",
      quantity: 79.0,
      unit: "mg",
    },
    CA: {
      label: "Calcium, Ca",
      quantity: 13.0,
      unit: "mg",
    },
    MG: {
      label: "Magnesium, Mg",
      quantity: 21.0,
      unit: "mg",
    },
    K: {
      label: "Potassium, K",
      quantity: 373.0,
      unit: "mg",
    },
    FE: {
      label: "Iron, Fe",
      quantity: 2.09,
      unit: "mg",
    },
    ZN: {
      label: "Zinc, Zn",
      quantity: 5.41,
      unit: "mg",
    },
    P: {
      label: "Phosphorus, P",
      quantity: 217.0,
      unit: "mg",
    },
    VITA_RAE: {
      label: "Vitamin A, RAE",
      quantity: 2.0,
      unit: "µg",
    },
    VITC: {
      label: "Vitamin C, total ascorbic acid",
      quantity: 0.0,
      unit: "mg",
    },
    THIA: {
      label: "Thiamin",
      quantity: 0.08,
      unit: "mg",
    },
    RIBF: {
      label: "Riboflavin",
      quantity: 0.17,
      unit: "mg",
    },
    NIA: {
      label: "Niacin",
      quantity: 4.887,
      unit: "mg",
    },
    VITB6A: {
      label: "Vitamin B-6",
      quantity: 0.568,
      unit: "mg",
    },
    FOLDFE: {
      label: "Folate, DFE",
      quantity: 3.0,
      unit: "µg",
    },
    FOLFD: {
      label: "Folate, food",
      quantity: 3.0,
      unit: "µg",
    },
    FOLAC: {
      label: "Folic acid",
      quantity: 0.0,
      unit: "µg",
    },
    VITB12: {
      label: "Vitamin B-12",
      quantity: 2.27,
      unit: "µg",
    },
    VITD: {
      label: "Vitamin D (D2 + D3)",
      quantity: 0.1,
      unit: "µg",
    },
    TOCPHA: {
      label: "Vitamin E (alpha-tocopherol)",
      quantity: 0.18,
      unit: "mg",
    },
    VITK1: {
      label: "Vitamin K (phylloquinone)",
      quantity: 1.5,
      unit: "µg",
    },
    WATER: {
      label: "Water",
      quantity: 72.32,
      unit: "g",
    },
  },
  totalDaily: {
    ENERC_KCAL: {
      label: "Energy",
      quantity: 6.5,
      unit: "%",
    },
    FAT: {
      label: "Fat",
      quantity: 7.3999999999999995,
      unit: "%",
    },
    FASAT: {
      label: "Saturated",
      quantity: 9.940000000000001,
      unit: "%",
    },
    CHOCDF: {
      label: "Carbs",
      quantity: 0.04,
      unit: "%",
    },
    FIBTG: {
      label: "Fiber",
      quantity: 0.0,
      unit: "%",
    },
    PROCNT: {
      label: "Protein",
      quantity: 43.28,
      unit: "%",
    },
    CHOLE: {
      label: "Cholesterol",
      quantity: 21.0,
      unit: "%",
    },
    NA: {
      label: "Sodium",
      quantity: 3.2916666666666665,
      unit: "%",
    },
    CA: {
      label: "Calcium",
      quantity: 1.3,
      unit: "%",
    },
    MG: {
      label: "Magnesium",
      quantity: 5.0,
      unit: "%",
    },
    K: {
      label: "Potassium",
      quantity: 7.9361702127659575,
      unit: "%",
    },
    FE: {
      label: "Iron",
      quantity: 11.61111111111111,
      unit: "%",
    },
    ZN: {
      label: "Zinc",
      quantity: 49.18181818181818,
      unit: "%",
    },
    P: {
      label: "Phosphorus",
      quantity: 31.0,
      unit: "%",
    },
    VITA_RAE: {
      label: "Vitamin A",
      quantity: 0.2222222222222222,
      unit: "%",
    },
    VITC: {
      label: "Vitamin C",
      quantity: 0.0,
      unit: "%",
    },
    THIA: {
      label: "Thiamin (B1)",
      quantity: 6.666666666666667,
      unit: "%",
    },
    RIBF: {
      label: "Riboflavin (B2)",
      quantity: 13.076923076923077,
      unit: "%",
    },
    NIA: {
      label: "Niacin (B3)",
      quantity: 30.543749999999996,
      unit: "%",
    },
    VITB6A: {
      label: "Vitamin B6",
      quantity: 43.692307692307686,
      unit: "%",
    },
    FOLDFE: {
      label: "Folate equivalent (total)",
      quantity: 0.75,
      unit: "%",
    },
    VITB12: {
      label: "Vitamin B12",
      quantity: 94.58333333333334,
      unit: "%",
    },
    VITD: {
      label: "Vitamin D",
      quantity: 0.6666666666666666,
      unit: "%",
    },
    TOCPHA: {
      label: "Vitamin E",
      quantity: 1.2,
      unit: "%",
    },
    VITK1: {
      label: "Vitamin K",
      quantity: 1.25,
      unit: "%",
    },
  },
  totalNutrientsKCal: {
    ENERC_KCAL: {
      label: "Energy",
      quantity: 129,
      unit: "kcal",
    },
    PROCNT_KCAL: {
      label: "Calories from protein",
      quantity: 86,
      unit: "kcal",
    },
    FAT_KCAL: {
      label: "Calories from fat",
      quantity: 43,
      unit: "kcal",
    },
    CHOCDF_KCAL: {
      label: "Calories from carbohydrates",
      quantity: 0,
      unit: "kcal",
    },
  },
};

export const chocolateData: NutritionDetailsAPIModel = {
  uri: "http://www.edamam.com/ontologies/edamam.owl#recipe_eb5d2a1884fb4896a391412207b39019",
  yield: 4.0,
  calories: 480,
  totalWeight: 100.0,
  dietLabels: ["LOW_SODIUM"],
  healthLabels: [
    "LOW_POTASSIUM",
    "KIDNEY_FRIENDLY",
    "VEGAN",
    "VEGETARIAN",
    "PESCATARIAN",
    "PALEO",
    "DAIRY_FREE",
    "GLUTEN_FREE",
    "WHEAT_FREE",
    "EGG_FREE",
    "MILK_FREE",
    "PEANUT_FREE",
    "TREE_NUT_FREE",
    "SOY_FREE",
    "FISH_FREE",
    "SHELLFISH_FREE",
    "PORK_FREE",
    "RED_MEAT_FREE",
    "CRUSTACEAN_FREE",
    "CELERY_FREE",
    "MUSTARD_FREE",
    "SESAME_FREE",
    "LUPINE_FREE",
    "MOLLUSK_FREE",
    "ALCOHOL_FREE",
    "SULPHITE_FREE",
    "KOSHER",
  ],
  cautions: ["SULFITES"],
  totalNutrients: {
    ENERC_KCAL: {
      label: "Energy",
      quantity: 480.0,
      unit: "kcal",
    },
    FAT: {
      label: "Total lipid (fat)",
      quantity: 30.0,
      unit: "g",
    },
    FASAT: {
      label: "Fatty acids, total saturated",
      quantity: 17.75,
      unit: "g",
    },
    FAMS: {
      label: "Fatty acids, total monounsaturated",
      quantity: 9.966,
      unit: "g",
    },
    FAPU: {
      label: "Fatty acids, total polyunsaturated",
      quantity: 0.966,
      unit: "g",
    },
    CHOCDF: {
      label: "Carbohydrate, by difference",
      quantity: 63.9,
      unit: "g",
    },
    FIBTG: {
      label: "Fiber, total dietary",
      quantity: 5.9,
      unit: "g",
    },
    SUGAR: {
      label: "Sugars, total",
      quantity: 54.5,
      unit: "g",
    },
    "SUGAR.added": {
      label: "Sugars, added",
      quantity: 54.5,
      unit: "g",
    },
    PROCNT: {
      label: "Protein",
      quantity: 4.2,
      unit: "g",
    },
    CHOLE: {
      label: "Cholesterol",
      quantity: 0.0,
      unit: "mg",
    },
    NA: {
      label: "Sodium, Na",
      quantity: 11.0,
      unit: "mg",
    },
    CA: {
      label: "Calcium, Ca",
      quantity: 32.0,
      unit: "mg",
    },
    MG: {
      label: "Magnesium, Mg",
      quantity: 115.0,
      unit: "mg",
    },
    K: {
      label: "Potassium, K",
      quantity: 365.0,
      unit: "mg",
    },
    FE: {
      label: "Iron, Fe",
      quantity: 3.13,
      unit: "mg",
    },
    ZN: {
      label: "Zinc, Zn",
      quantity: 1.62,
      unit: "mg",
    },
    P: {
      label: "Phosphorus, P",
      quantity: 132.0,
      unit: "mg",
    },
    VITA_RAE: {
      label: "Vitamin A, RAE",
      quantity: 0.0,
      unit: "µg",
    },
    VITC: {
      label: "Vitamin C, total ascorbic acid",
      quantity: 0.0,
      unit: "mg",
    },
    THIA: {
      label: "Thiamin",
      quantity: 0.055,
      unit: "mg",
    },
    RIBF: {
      label: "Riboflavin",
      quantity: 0.09,
      unit: "mg",
    },
    NIA: {
      label: "Niacin",
      quantity: 0.427,
      unit: "mg",
    },
    VITB6A: {
      label: "Vitamin B-6",
      quantity: 0.035,
      unit: "mg",
    },
    FOLDFE: {
      label: "Folate, DFE",
      quantity: 13.0,
      unit: "µg",
    },
    FOLFD: {
      label: "Folate, food",
      quantity: 13.0,
      unit: "µg",
    },
    FOLAC: {
      label: "Folic acid",
      quantity: 0.0,
      unit: "µg",
    },
    VITB12: {
      label: "Vitamin B-12",
      quantity: 0.0,
      unit: "µg",
    },
    VITD: {
      label: "Vitamin D (D2 + D3)",
      quantity: 0.0,
      unit: "µg",
    },
    TOCPHA: {
      label: "Vitamin E (alpha-tocopherol)",
      quantity: 0.26,
      unit: "mg",
    },
    VITK1: {
      label: "Vitamin K (phylloquinone)",
      quantity: 5.6,
      unit: "µg",
    },
    WATER: {
      label: "Water",
      quantity: 0.7,
      unit: "g",
    },
  },
  totalDaily: {
    ENERC_KCAL: {
      label: "Energy",
      quantity: 24.0,
      unit: "%",
    },
    FAT: {
      label: "Fat",
      quantity: 46.15384615384615,
      unit: "%",
    },
    FASAT: {
      label: "Saturated",
      quantity: 88.75,
      unit: "%",
    },
    CHOCDF: {
      label: "Carbs",
      quantity: 21.3,
      unit: "%",
    },
    FIBTG: {
      label: "Fiber",
      quantity: 23.6,
      unit: "%",
    },
    PROCNT: {
      label: "Protein",
      quantity: 8.4,
      unit: "%",
    },
    CHOLE: {
      label: "Cholesterol",
      quantity: 0.0,
      unit: "%",
    },
    NA: {
      label: "Sodium",
      quantity: 0.4583333333333333,
      unit: "%",
    },
    CA: {
      label: "Calcium",
      quantity: 3.2,
      unit: "%",
    },
    MG: {
      label: "Magnesium",
      quantity: 27.38095238095238,
      unit: "%",
    },
    K: {
      label: "Potassium",
      quantity: 7.76595744680851,
      unit: "%",
    },
    FE: {
      label: "Iron",
      quantity: 17.38888888888889,
      unit: "%",
    },
    ZN: {
      label: "Zinc",
      quantity: 14.727272727272727,
      unit: "%",
    },
    P: {
      label: "Phosphorus",
      quantity: 18.857142857142858,
      unit: "%",
    },
    VITA_RAE: {
      label: "Vitamin A",
      quantity: 0.0,
      unit: "%",
    },
    VITC: {
      label: "Vitamin C",
      quantity: 0.0,
      unit: "%",
    },
    THIA: {
      label: "Thiamin (B1)",
      quantity: 4.583333333333334,
      unit: "%",
    },
    RIBF: {
      label: "Riboflavin (B2)",
      quantity: 6.9230769230769225,
      unit: "%",
    },
    NIA: {
      label: "Niacin (B3)",
      quantity: 2.6687499999999997,
      unit: "%",
    },
    VITB6A: {
      label: "Vitamin B6",
      quantity: 2.6923076923076925,
      unit: "%",
    },
    FOLDFE: {
      label: "Folate equivalent (total)",
      quantity: 3.25,
      unit: "%",
    },
    VITB12: {
      label: "Vitamin B12",
      quantity: 0.0,
      unit: "%",
    },
    VITD: {
      label: "Vitamin D",
      quantity: 0.0,
      unit: "%",
    },
    TOCPHA: {
      label: "Vitamin E",
      quantity: 1.7333333333333334,
      unit: "%",
    },
    VITK1: {
      label: "Vitamin K",
      quantity: 4.666666666666667,
      unit: "%",
    },
  },
  totalNutrientsKCal: {
    ENERC_KCAL: {
      label: "Energy",
      quantity: 480,
      unit: "kcal",
    },
    PROCNT_KCAL: {
      label: "Calories from protein",
      quantity: 15,
      unit: "kcal",
    },
    FAT_KCAL: {
      label: "Calories from fat",
      quantity: 239,
      unit: "kcal",
    },
    CHOCDF_KCAL: {
      label: "Calories from carbohydrates",
      quantity: 226,
      unit: "kcal",
    },
  },
};
