on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Setup node
        uses: actions/setup-node@v3
        with: 
          node-version: 16 # check this
          cache: npm
        
      - name: Install dependencies
        run: npm ci 

      - name: Lint
        run: npm run lint

      - name: Unit test
        run: npm run test:unit

      